languageCode = "pt-br"
defaultContentLanguage = "pt-br"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.158.0"
disableKinds = ["RSS"]
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      
