[module]
  [module.hugoVersion]
    extended = true
    min = "0.158.0"
    languageCode = "pt-br"
    defaultContentLanguage = "pt-BR"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
